name: analytics_inspector
description: Analytics Inspector kit for flutter_ume.
version: 0.0.1
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume: ">=1.0.0 <2.0.0"

  appmetrica_plugin: 1.4.0
  freezed: 2.2.0
  freezed_annotation: 2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.12
  build_runner: 2.4.5
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65


