name: flutter_ume
description: UME is an in-app debug kits platform for Flutter apps. Produced by Flutter Infra team of ByteDance.
version: 1.1.2
publish_to: none
homepage: https://github.com/suxoikorm/flutter_ume

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.0.15
  vm_service: ^13.0.0
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65
  lints: ^2.0.0

flutter:
