name: flutter_ume_kit_channel_monitor
description: channel monitor kit for flutter_ume
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    path: ../..
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=1.0.0 <3.0.0"

flutter:
