name: errors_inspector
description: Errors inspector for flutter_ume.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=3.22.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    path: ../..
