name: errors_inspector
description: Errors inspector for flutter_ume.
version: 0.0.1
homepage: https://github.com/bytedance/flutter_ume

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git:
      url: https://github.com/suxoikorm/flutter_ume
